DSE 6.8.27
datastax/release-notes pull request #71
Opened 2022-10-21 02:21 UTC by devoshmathivanan

Release notes for DSE 6.8.27

2022-10-21 11:11 UTC, tiagomlalves requested changes
All CVE tickets should appear under the CVE section. I'm not sure at the moment if this is a change needed in the `release-notes-generator` or if the tickets are not properly filled. I'll give it a look on Monday.

2022-10-25 10:42 UTC, devoshmathivanan commented
> All CVE tickets should appear under the CVE section. I'm not sure at the moment if this is a change needed in the `release-notes-generator` or if the tickets are not properly filled. I'll give it a look on Monday.

This is something generated by the release-notes generator. The release notes of the 6.8.25 version also contain CVE tickets under other components.

2022-10-25 21:02 UTC, thobe approved these changes
Some tickets had been tagged with the wrong component. After fixing that all things end up in the right place in the release notes.

2022-10-25 21:18 UTC, tiagomlalves approved these changes

2022-10-25 21:25 UTC, merged